openapi: 3.0.0
info:
  title: Direct S3 API
  version: 1.0.0
servers:
  - url: https://s3.{region}.amazonaws.com
    variables:
      region:
        default: us-east-1
paths:
  /{bucket}/{key}:
    get:
      summary: Get object from S3
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: key
          in: path
          required: true
          schema:
            type: string
      security:
        - awsv4: []
      responses:
        '200':
          description: Successful response
    put:
      summary: Upload object to S3
      parameters:
        - name: bucket
          in: path
          required: true
          schema:
            type: string
        - name: key
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      security:
        - awsv4: []
      responses:
        '200':
          description: Successfully uploaded

components:
  securitySchemes:
    awsv4:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: awsSigv4
